"use client";

import { useSyncExternalStore } from "react";
import { baseName } from "@spire/types";

/**
 * Trimmed material-icon-theme manifest, fetched once from
 * `/file-icons/manifest.json` (generated by scripts/copy-file-icons.mjs). Icon
 * names map 1:1 to `<name>.svg` under the same public folder.
 */
export type IconManifest = {
    file: string;
    folder: string;
    folderExpanded: string;
    fileNames: Record<string, string>;
    fileExtensions: Record<string, string>;
    folderNames: Record<string, string>;
    folderNamesExpanded: Record<string, string>;
};

let manifest: IconManifest | null = null;
let loadStarted = false;
const listeners = new Set<() => void>();

function ensureLoaded() {
    if (loadStarted || typeof window === "undefined") {
        return;
    }
    loadStarted = true;
    void fetch("/file-icons/manifest.json")
        .then((response) => (response.ok ? (response.json() as Promise<IconManifest>) : null))
        .then((data) => {
            if (data) {
                manifest = data;
                for (const listener of listeners) {
                    listener();
                }
            }
        })
        .catch(() => {
            /**
             * A failed fetch leaves the manifest null. All icon consumers check for
             * null and fall back to generic lucide icons, so the UI degrades gracefully.
             */
        });
}

function subscribe(onChange: () => void) {
    listeners.add(onChange);
    ensureLoaded();
    return () => {
        listeners.delete(onChange);
    };
}

/** Subscribe to the lazily-loaded icon manifest; null until it resolves. */
export function useIconManifest(): IconManifest | null {
    return useSyncExternalStore(
        subscribe,
        () => manifest,
        () => null
    );
}

/** Resolve a file name/path to a material icon name (longest extension wins). */
export function fileIconName(manifest: IconManifest | null, path: string): string | null {
    if (!manifest) {
        return null;
    }
    const name = baseName(path).toLowerCase();
    const byName = manifest.fileNames[name];
    if (byName) {
        return byName;
    }
    const parts = name.split(".");
    for (let i = 1; i < parts.length; i += 1) {
        const ext = parts.slice(i).join(".");
        const byExt = manifest.fileExtensions[ext];
        if (byExt) {
            return byExt;
        }
    }
    return manifest.file;
}

/** Resolve a folder name to a material icon name, collapsed or expanded. */
export function folderIconName(
    manifest: IconManifest | null,
    path: string,
    expanded: boolean
): string | null {
    if (!manifest) {
        return null;
    }
    const name = baseName(path).toLowerCase();
    if (expanded) {
        return manifest.folderNamesExpanded[name] ?? manifest.folderExpanded;
    }
    return manifest.folderNames[name] ?? manifest.folder;
}

export function iconUrl(name: string | null): string | null {
    return name ? `/file-icons/${name}.svg` : null;
}
